<?php

declare(strict_types=1);

namespace MageSuite\LowestPriceLogger\Test\Integration\Setup\Patch\Data;

#[\Magento\TestFramework\Fixture\DbIsolation(false)]
#[\Magento\TestFramework\Fixture\AppIsolation(true)]
#[\Magento\TestFramework\Fixture\DataFixture('MageSuite_LowestPriceLogger::Test/Integration/_files/product.php')]
class MigratePriceHistoryToWebsiteTablesTest extends \PHPUnit\Framework\TestCase
{
    protected \Magento\Framework\App\ObjectManager $objectManager;
    protected \MageSuite\LowestPriceLogger\Setup\Patch\Data\MigratePriceHistoryToWebsiteTables $patch;
    protected \MageSuite\LowestPriceLogger\Model\TableMaintainer $tableMaintainer;
    protected \MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog $priceHistoryLog;
    protected \Magento\Framework\App\ResourceConnection $resourceConnection;
    protected \Magento\Store\Model\WebsiteFactory $websiteFactory;
    protected \Magento\Catalog\Api\ProductRepositoryInterface $productRepository;

    protected function setUp(): void
    {
        $this->objectManager = \Magento\TestFramework\ObjectManager::getInstance();
        $this->patch = $this->objectManager->get(\MageSuite\LowestPriceLogger\Setup\Patch\Data\MigratePriceHistoryToWebsiteTables::class);
        $this->tableMaintainer = $this->objectManager->get(\MageSuite\LowestPriceLogger\Model\TableMaintainer::class);
        $this->priceHistoryLog = $this->objectManager->get(\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog::class);
        $this->resourceConnection = $this->objectManager->get(\Magento\Framework\App\ResourceConnection::class);
        $this->websiteFactory = $this->objectManager->create(\Magento\Store\Model\WebsiteFactory::class);
        $this->productRepository = $this->objectManager->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
    }

    protected function tearDown(): void
    {
        $connection = $this->resourceConnection->getConnection();
        $connection->delete($connection->getTableName('price_history_log'));
        $this->priceHistoryLog->cleanTable();
    }

    public function testDataMigratesFromGlobalTableToPerWebsiteTables(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();
        $secondWebsiteId = $this->getSecondWebsiteId();
        $connection = $this->resourceConnection->getConnection();
        $legacyTable = $connection->getTableName('price_history_log');

        $connection->insertMultiple($legacyTable, [
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $defaultWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 10.00,
                'log_date' => '2024-01-01',
                'was_autogenerated_by_cron' => 1,
            ],
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $secondWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 8.00,
                'log_date' => '2024-01-01',
                'was_autogenerated_by_cron' => 1,
            ],
        ]);

        $this->patch->apply();

        $this->assertSame(1, $this->countRowsInWebsiteTable($defaultWebsiteId));
        $this->assertSame(1, $this->countRowsInWebsiteTable($secondWebsiteId));
    }

    public function testRerunningPatchDoesNotDuplicateRows(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();
        $connection = $this->resourceConnection->getConnection();
        $legacyTable = $connection->getTableName('price_history_log');

        $connection->insert($legacyTable, [
            'product_id' => (int) $product->getId(),
            'website_id' => $defaultWebsiteId,
            'customer_group_id' => 0,
            'price_type' => 0,
            'price' => 10.00,
            'log_date' => '2024-01-01',
            'was_autogenerated_by_cron' => 1,
        ]);

        $this->patch->apply();
        $this->patch->apply();

        $this->assertSame(1, $this->countRowsInWebsiteTable($defaultWebsiteId));
    }

    protected function countRowsInWebsiteTable(int $websiteId): int
    {
        $tableName = $this->tableMaintainer->getTableNameForWebsite($websiteId);

        return (int) $this->resourceConnection->getConnection()->fetchOne(
            $this->resourceConnection->getConnection()->select()->from($tableName, ['COUNT(*)'])
        );
    }

    protected function getDefaultWebsiteId(): int
    {
        return (int) $this->websiteFactory->create()->load('base', 'code')->getId();
    }

    protected function getSecondWebsiteId(): int
    {
        return (int) $this->websiteFactory->create()->load('test', 'code')->getId();
    }
}
