<?php

declare(strict_types=1);

namespace MageSuite\LowestPriceLogger\Test\Integration\Plugin\Store\Model\ResourceModel\Website;

#[\Magento\TestFramework\Fixture\DbIsolation(false)]
#[\Magento\TestFramework\Fixture\AppIsolation(true)]
#[\Magento\TestFramework\Fixture\AppArea('adminhtml')]
class ManagePriceHistoryTablesTest extends \PHPUnit\Framework\TestCase
{
    protected \Magento\Framework\App\ObjectManager $objectManager;
    protected \MageSuite\LowestPriceLogger\Model\TableMaintainer $tableMaintainer;
    protected \Magento\Framework\App\ResourceConnection $resourceConnection;

    protected function setUp(): void
    {
        $this->objectManager = \Magento\TestFramework\ObjectManager::getInstance();
        $this->tableMaintainer = $this->objectManager->get(\MageSuite\LowestPriceLogger\Model\TableMaintainer::class);
        $this->resourceConnection = $this->objectManager->get(\Magento\Framework\App\ResourceConnection::class);
    }

    public function testTableIsCreatedWhenNewWebsiteIsSaved(): void
    {
        $website = $this->objectManager->create(\Magento\Store\Model\Website::class);
        $website->setData(['code' => 'test_plugin_new', 'name' => 'Test Plugin New', 'is_default' => 0]);
        $website->save();

        try {
            $this->assertTrue(
                $this->resourceConnection->getConnection()->isTableExists(
                    $this->tableMaintainer->getTableNameForWebsite((int) $website->getId())
                )
            );
        } finally {
            $website->delete();
        }
    }

    public function testTableIsDroppedWhenWebsiteIsDeleted(): void
    {
        $website = $this->objectManager->create(\Magento\Store\Model\Website::class);
        $website->setData(['code' => 'test_plugin_del', 'name' => 'Test Plugin Delete', 'is_default' => 0]);
        $website->save();
        $websiteId = (int) $website->getId();

        $website->delete();

        $this->assertFalse(
            $this->resourceConnection->getConnection()->isTableExists(
                $this->tableMaintainer->getTableNameForWebsite($websiteId)
            )
        );
    }

    public function testResavingExistingWebsiteDoesNotDropTable(): void
    {
        $website = $this->objectManager->create(\Magento\Store\Model\Website::class);
        $website->setData(['code' => 'test_plugin_resave', 'name' => 'Test Plugin Resave', 'is_default' => 0]);
        $website->save();

        try {
            $websiteId = (int) $website->getId();
            $tableName = $this->tableMaintainer->getTableNameForWebsite($websiteId);

            $this->resourceConnection->getConnection()->insert($tableName, [
                'product_id' => 1,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 9.99,
                'log_date' => '2024-01-01',
                'was_autogenerated_by_cron' => 0,
            ]);

            $website->setName('Test Plugin Resave Updated');
            $website->save();

            $rowCount = (int) $this->resourceConnection->getConnection()->fetchOne(
                $this->resourceConnection->getConnection()->select()->from($tableName, ['COUNT(*)'])
            );
            $this->assertSame(1, $rowCount);
        } finally {
            $website->delete();
        }
    }
}