<?php

namespace MageSuite\LowestPriceLogger\Ui\Component\Listing\Column;

class LogOrigin extends \Magento\Ui\Component\Listing\Columns\Column
{
    public function prepareDataSource(array $dataSource)
    {
        if (!isset($dataSource['data']['items'])) {
            return $dataSource;
        }

        $fieldName = $this->getData('name');

        foreach ($dataSource['data']['items'] as & $item) {
            $item[$fieldName] = $item[$fieldName] ? __('Auto generated by cron') : __('Price seen by user');
        }

        return $dataSource;
    }
}
