<?php

declare(strict_types=1);

namespace MageSuite\LowestPriceLogger\Setup\Patch\Data;

class MigratePriceHistoryToWebsiteTables implements \Magento\Framework\Setup\Patch\DataPatchInterface
{
    protected const COLUMNS = [
        'customer_group_id',
        'product_id',
        'price_type',
        'price',
        'log_date',
        'was_autogenerated_by_cron'
    ];

    public function __construct(
        protected \Magento\Framework\App\ResourceConnection $resourceConnection,
        protected \MageSuite\LowestPriceLogger\Model\TableMaintainer $tableMaintainer,
        protected \Magento\Store\Model\StoreManagerInterface $storeManager
    ) {
    }

    public function apply(): self
    {
        $connection = $this->resourceConnection->getConnection();
        $sourceTable = $connection->getTableName('price_history_log');

        try {
            foreach ($this->storeManager->getWebsites() as $website) {
                $websiteId = (int) $website->getId();

                $select = $connection->select()
                    ->from($sourceTable, self::COLUMNS)
                    ->where('website_id = ?', $websiteId);

                $connection->query($connection->insertFromSelect(
                    $select,
                    $this->tableMaintainer->getTableNameForWebsite($websiteId),
                    self::COLUMNS,
                    \Magento\Framework\DB\Adapter\AdapterInterface::INSERT_IGNORE
                ));
            }
        } catch (\Throwable $e) {
            throw $e;
        }

        return $this;
    }

    public static function getDependencies(): array
    {
        return [];
    }

    public function getAliases(): array
    {
        return [];
    }
}
