<?php

declare(strict_types=1);

namespace MageSuite\LowestPriceLogger\Test\Integration\Cron;

#[\Magento\TestFramework\Fixture\DbIsolation(false)]
#[\Magento\TestFramework\Fixture\AppIsolation(true)]
#[\Magento\TestFramework\Fixture\DataFixture('MageSuite_LowestPriceLogger::Test/Integration/_files/product.php')]
class LogsCleanupTest extends \PHPUnit\Framework\TestCase
{
    protected \Magento\Framework\App\ObjectManager $objectManager;
    protected \MageSuite\LowestPriceLogger\Cron\LogsCleanup $logsCleanup;
    protected \MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog $priceHistoryLog;
    protected \MageSuite\LowestPriceLogger\Model\TableMaintainer $tableMaintainer;
    protected \Magento\Framework\App\ResourceConnection $resourceConnection;
    protected \Magento\Store\Model\WebsiteFactory $websiteFactory;
    protected \Magento\Catalog\Api\ProductRepositoryInterface $productRepository;

    protected function setUp(): void
    {
        $this->objectManager = \Magento\TestFramework\ObjectManager::getInstance();
        $this->logsCleanup = $this->objectManager->get(\MageSuite\LowestPriceLogger\Cron\LogsCleanup::class);
        $this->priceHistoryLog = $this->objectManager->get(\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog::class);
        $this->tableMaintainer = $this->objectManager->get(\MageSuite\LowestPriceLogger\Model\TableMaintainer::class);
        $this->resourceConnection = $this->objectManager->get(\Magento\Framework\App\ResourceConnection::class);
        $this->websiteFactory = $this->objectManager->create(\Magento\Store\Model\WebsiteFactory::class);
        $this->productRepository = $this->objectManager->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
    }

    protected function tearDown(): void
    {
        $this->priceHistoryLog->cleanTable();
    }

    #[\Magento\TestFramework\Fixture\Config('lowest_price_logger/cleanup_cron/enabled', 1)]
    #[\Magento\TestFramework\Fixture\Config('lowest_price_logger/cleanup_cron/retention_period_in_days', 30)]
    public function testCleanupRemovesRecordsOlderThanRetentionPeriodFromAllWebsites(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();
        $secondWebsiteId = $this->getSecondWebsiteId();

        $this->priceHistoryLog->addPricesToLog([
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $defaultWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 10.00,
                'log_date' => date('Y-m-d', strtotime('-60 days')),
                'was_autogenerated_by_cron' => 1,
            ],
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $secondWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 8.00,
                'log_date' => date('Y-m-d', strtotime('-60 days')),
                'was_autogenerated_by_cron' => 1,
            ],
        ]);

        $this->logsCleanup->execute();

        $this->assertSame(0, $this->countRowsInWebsiteTable($defaultWebsiteId));
        $this->assertSame(0, $this->countRowsInWebsiteTable($secondWebsiteId));
    }

    #[\Magento\TestFramework\Fixture\Config('lowest_price_logger/cleanup_cron/enabled', 1)]
    #[\Magento\TestFramework\Fixture\Config('lowest_price_logger/cleanup_cron/retention_period_in_days', 30)]
    public function testCleanupKeepsRecordsWithinRetentionPeriod(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();

        $this->priceHistoryLog->addPricesToLog([
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $defaultWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 10.00,
                'log_date' => date('Y-m-d', strtotime('-60 days')),
                'was_autogenerated_by_cron' => 1,
            ],
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $defaultWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 11.00,
                'log_date' => date('Y-m-d'),
                'was_autogenerated_by_cron' => 1,
            ],
        ]);

        $this->logsCleanup->execute();

        $this->assertSame(1, $this->countRowsInWebsiteTable($defaultWebsiteId));
    }

    #[\Magento\TestFramework\Fixture\Config('lowest_price_logger/cleanup_cron/enabled', 0)]
    #[\Magento\TestFramework\Fixture\Config('lowest_price_logger/cleanup_cron/retention_period_in_days', 30)]
    public function testCleanupDoesNothingWhenDisabled(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();

        $this->priceHistoryLog->addPricesToLog([[
            'product_id' => (int) $product->getId(),
            'website_id' => $defaultWebsiteId,
            'customer_group_id' => 0,
            'price_type' => 0,
            'price' => 10.00,
            'log_date' => date('Y-m-d', strtotime('-60 days')),
            'was_autogenerated_by_cron' => 1,
        ]]);

        $this->logsCleanup->execute();

        $this->assertSame(1, $this->countRowsInWebsiteTable($defaultWebsiteId));
    }

    protected function countRowsInWebsiteTable(int $websiteId): int
    {
        $tableName = $this->tableMaintainer->getTableNameForWebsite($websiteId);

        return (int) $this->resourceConnection->getConnection()->fetchOne(
            $this->resourceConnection->getConnection()->select()->from($tableName, ['COUNT(*)'])
        );
    }

    protected function getDefaultWebsiteId(): int
    {
        return (int) $this->websiteFactory->create()->load('base', 'code')->getId();
    }

    protected function getSecondWebsiteId(): int
    {
        return (int) $this->websiteFactory->create()->load('test', 'code')->getId();
    }
}