<?php

declare(strict_types=1);

namespace MageSuite\LowestPriceLogger\Test\Integration\Model\ResourceModel;

#[\Magento\TestFramework\Fixture\DbIsolation(false)]
#[\Magento\TestFramework\Fixture\AppIsolation(true)]
#[\Magento\TestFramework\Fixture\DataFixture('MageSuite_LowestPriceLogger::Test/Integration/_files/product.php')]
class PriceHistoryLogMultiWebsiteTest extends \PHPUnit\Framework\TestCase
{
    protected \Magento\Framework\App\ObjectManager $objectManager;
    protected \MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog $priceHistoryLog;
    protected \MageSuite\LowestPriceLogger\Model\TableMaintainer $tableMaintainer;
    protected \Magento\Framework\App\ResourceConnection $resourceConnection;
    protected \Magento\Store\Model\WebsiteFactory $websiteFactory;
    protected \Magento\Catalog\Api\ProductRepositoryInterface $productRepository;

    protected function setUp(): void
    {
        $this->objectManager = \Magento\TestFramework\ObjectManager::getInstance();
        $this->priceHistoryLog = $this->objectManager->get(\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog::class);
        $this->tableMaintainer = $this->objectManager->get(\MageSuite\LowestPriceLogger\Model\TableMaintainer::class);
        $this->resourceConnection = $this->objectManager->get(\Magento\Framework\App\ResourceConnection::class);
        $this->websiteFactory = $this->objectManager->create(\Magento\Store\Model\WebsiteFactory::class);
        $this->productRepository = $this->objectManager->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
    }

    protected function tearDown(): void
    {
        $this->priceHistoryLog->cleanTable();
    }

    public function testAddPricesToLogIsolatesDataByWebsite(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();
        $secondWebsiteId = $this->getSecondWebsiteId();

        $this->priceHistoryLog->addPricesToLog([[
            'product_id' => (int) $product->getId(),
            'website_id' => $defaultWebsiteId,
            'customer_group_id' => 0,
            'price_type' => 0,
            'price' => 10.00,
            'log_date' => date('Y-m-d'),
            'was_autogenerated_by_cron' => 1,
        ]]);

        $this->assertCount(
            1,
            $this->priceHistoryLog->getPriceHistory([(int) $product->getId()], $defaultWebsiteId, 0)
        );
        $this->assertEmpty(
            $this->priceHistoryLog->getPriceHistory([(int) $product->getId()], $secondWebsiteId, 0)
        );
    }

    public function testGetPriceHistoryReturnsOnlyRequestedWebsiteData(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();
        $secondWebsiteId = $this->getSecondWebsiteId();

        $this->priceHistoryLog->addPricesToLog([
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $defaultWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 10.00,
                'log_date' => date('Y-m-d'),
                'was_autogenerated_by_cron' => 1,
            ],
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $secondWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 8.00,
                'log_date' => date('Y-m-d'),
                'was_autogenerated_by_cron' => 1,
            ],
        ]);

        $defaultHistory = $this->priceHistoryLog->getPriceHistory([(int) $product->getId()], $defaultWebsiteId, 0);
        $secondHistory = $this->priceHistoryLog->getPriceHistory([(int) $product->getId()], $secondWebsiteId, 0);

        $this->assertCount(1, $defaultHistory);
        $this->assertEquals(10.00, $defaultHistory[0]['price']);
        $this->assertCount(1, $secondHistory);
        $this->assertEquals(8.00, $secondHistory[0]['price']);
    }

    public function testDeleteOlderThanDeletesFromAllWebsiteTables(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();
        $secondWebsiteId = $this->getSecondWebsiteId();

        $this->priceHistoryLog->addPricesToLog([
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $defaultWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 10.00,
                'log_date' => date('Y-m-d', strtotime('-60 days')),
                'was_autogenerated_by_cron' => 1,
            ],
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $secondWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 8.00,
                'log_date' => date('Y-m-d', strtotime('-60 days')),
                'was_autogenerated_by_cron' => 1,
            ],
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $defaultWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 11.00,
                'log_date' => date('Y-m-d'),
                'was_autogenerated_by_cron' => 1,
            ],
        ]);

        $this->priceHistoryLog->deleteOlderThan(30);

        $this->assertSame(
            1,
            $this->countRowsInWebsiteTable($defaultWebsiteId),
            'Only the recent record should remain in the default website table'
        );
        $this->assertSame(
            0,
            $this->countRowsInWebsiteTable($secondWebsiteId),
            'All records should be removed from the second website table'
        );
    }

    public function testGetLastPricesPerProductReturnsDataKeyedByWebsiteId(): void
    {
        $product = $this->productRepository->get('simple');
        $defaultWebsiteId = $this->getDefaultWebsiteId();
        $secondWebsiteId = $this->getSecondWebsiteId();

        $this->priceHistoryLog->addPricesToLog([
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $defaultWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 10.00,
                'log_date' => date('Y-m-d'),
                'was_autogenerated_by_cron' => 1,
            ],
            [
                'product_id' => (int) $product->getId(),
                'website_id' => $secondWebsiteId,
                'customer_group_id' => 0,
                'price_type' => 0,
                'price' => 8.00,
                'log_date' => date('Y-m-d'),
                'was_autogenerated_by_cron' => 1,
            ],
        ]);

        $result = $this->priceHistoryLog->getLastPricesPerProduct([(int) $product->getId()]);

        $productKey = (string) $product->getId();
        $this->assertArrayHasKey($productKey, $result);
        $this->assertArrayHasKey($defaultWebsiteId, $result[$productKey]['0']);
        $this->assertArrayHasKey($secondWebsiteId, $result[$productKey]['0']);
        $this->assertEquals(10.00, $result[$productKey]['0'][$defaultWebsiteId]['0']);
        $this->assertEquals(8.00, $result[$productKey]['0'][$secondWebsiteId]['0']);
    }

    protected function countRowsInWebsiteTable(int $websiteId): int
    {
        $tableName = $this->tableMaintainer->getTableNameForWebsite($websiteId);

        return (int) $this->resourceConnection->getConnection()->fetchOne(
            $this->resourceConnection->getConnection()->select()->from($tableName, ['COUNT(*)'])
        );
    }

    protected function getDefaultWebsiteId(): int
    {
        return (int) $this->websiteFactory->create()->load('base', 'code')->getId();
    }

    protected function getSecondWebsiteId(): int
    {
        return (int) $this->websiteFactory->create()->load('test', 'code')->getId();
    }
}