<?php

declare(strict_types=1);

namespace MageSuite\LowestPriceLogger\Test\Integration;

use Magento\TestFramework\Fixture\Config;
use Magento\TestFramework\Fixture\DbIsolation;

class AsyncLoggingTest extends \PHPUnit\Framework\TestCase
{
    protected ?\Magento\Framework\App\ObjectManager $objectManager;
    protected ?\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog $priceHistoryLog;
    protected ?\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryStagingLog $stagingLog;
    protected ?\MageSuite\LowestPriceLogger\Service\TransferStagedPricesToLog $transferStagedPricesToLog;
    protected ?GetCurrentDateFake $getCurrentDateFake;

    public function setUp(): void
    {
        $this->objectManager = \Magento\TestFramework\ObjectManager::getInstance();

        $this->getCurrentDateFake = new GetCurrentDateFake();
        $this->getCurrentDateFake->setValue('2024-01-15');
        $this->objectManager->addSharedInstance(
            $this->getCurrentDateFake,
            \MageSuite\LowestPriceLogger\Model\GetCurrentDate::class
        );

        $this->priceHistoryLog = $this->objectManager->get(
            \MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog::class
        );
        $this->stagingLog = $this->objectManager->get(
            \MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryStagingLog::class
        );
        $this->transferStagedPricesToLog = $this->objectManager->get(
            \MageSuite\LowestPriceLogger\Service\TransferStagedPricesToLog::class
        );

        $this->priceHistoryLog->cleanTable();
        $this->stagingLog->cleanTable();
    }

    #[DbIsolation(false)]
    public function testTransferServiceIsNoOpWhenAsyncDisabled()
    {
        $this->stagingLog->save([$this->buildPriceRow(1, 10.00)]);

        $this->transferStagedPricesToLog->execute();

        $this->assertNotEmpty($this->stagingLog->getBatch(100));
        $this->assertEmpty($this->priceHistoryLog->getPriceHistory([1]));
    }

    #[DbIsolation(false)]
    #[Config('lowest_price_logger/general/async_logging_enabled', 1)]
    #[Config('lowest_price_logger/processing/batch_size', 2)]
    public function testTransferServiceProcessesMultipleBatches()
    {
        $prices = [];
        for ($i = 0; $i < 5; $i++) {
            $prices[] = $this->buildPriceRow(1, 10.00 + $i);
        }
        $this->stagingLog->save($prices);

        $this->transferStagedPricesToLog->execute();

        $this->assertEmpty($this->stagingLog->getBatch(100));
        $this->assertCount(5, $this->priceHistoryLog->getPriceHistory([1]));
    }

    #[DbIsolation(false)]
    #[Config('lowest_price_logger/general/async_logging_enabled', 1)]
    public function testTransferServicePreservesAllPriceFieldsAfterDrain()
    {
        $this->stagingLog->save([$this->buildPriceRow(1, 29.99)]);

        $this->transferStagedPricesToLog->execute();

        $rows = $this->priceHistoryLog->getPriceHistory([1]);
        $this->assertCount(1, $rows);
        $this->assertEquals(1, $rows[0]['product_id']);
        $this->assertEquals(29.99, $rows[0]['price']);
        $this->assertEquals(1, $rows[0]['website_id']);
        $this->assertEquals(0, $rows[0]['customer_group_id']);
        $this->assertEquals('2024-01-01', $rows[0]['log_date']);
        $this->assertEquals(0, $rows[0]['was_autogenerated_by_cron']);
    }

    #[DbIsolation(false)]
    #[Config('lowest_price_logger/general/async_logging_enabled', 1)]
    public function testChangedPriceIsLoggedAfterSubsequentTransfer()
    {
        $this->stagingLog->save([$this->buildPriceRow(1, 10.00)]);
        $this->transferStagedPricesToLog->execute();

        $this->stagingLog->save([$this->buildPriceRow(1, 15.00)]);
        $this->transferStagedPricesToLog->execute();

        $rows = $this->priceHistoryLog->getPriceHistory([1]);
        $this->assertCount(2, $rows);
        $prices = array_column($rows, 'price');
        $this->assertContains('10.000000', $prices);
        $this->assertContains('15.000000', $prices);
    }

    public function tearDown(): void
    {
        $this->priceHistoryLog->cleanTable();
        $this->stagingLog->cleanTable();
    }

    protected function buildPriceRow(int $productId, float $price): array
    {
        return [
            'customer_group_id' => 0,
            'product_id' => $productId,
            'website_id' => 1,
            'price_type' => 0,
            'price' => $price,
            'log_date' => '2024-01-01',
            'was_autogenerated_by_cron' => 0,
        ];
    }
}