<?php

declare(strict_types=1);

namespace MageSuite\LowestPriceLogger\Test\Integration;

use Magento\TestFramework\Fixture\AppIsolation;
use Magento\TestFramework\Fixture\Config;
use Magento\TestFramework\Fixture\DataFixture;
use Magento\TestFramework\Fixture\DataFixtureStorageManager;
use Magento\TestFramework\Fixture\DbIsolation;

class AsyncLoggingFrontendTest extends \Magento\TestFramework\TestCase\AbstractController
{
    protected ?\Magento\Framework\App\ObjectManager $objectManager;
    protected ?\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog $priceHistoryLog;
    protected ?\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryStagingLog $stagingLog;
    protected ?\MageSuite\LowestPriceLogger\Service\TransferStagedPricesToLog $transferStagedPricesToLog;
    protected ?GetCurrentDateFake $getCurrentDateFake;

    public function setUp(): void
    {
        parent::setUp();

        $this->objectManager = \Magento\TestFramework\ObjectManager::getInstance();

        $this->getCurrentDateFake = new GetCurrentDateFake();
        $this->getCurrentDateFake->setValue('2024-01-15');
        $this->objectManager->addSharedInstance(
            $this->getCurrentDateFake,
            \MageSuite\LowestPriceLogger\Model\GetCurrentDate::class
        );

        $this->priceHistoryLog = $this->objectManager->get(
            \MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog::class
        );
        $this->stagingLog = $this->objectManager->get(
            \MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryStagingLog::class
        );
        $this->transferStagedPricesToLog = $this->objectManager->get(
            \MageSuite\LowestPriceLogger\Service\TransferStagedPricesToLog::class
        );

        $this->priceHistoryLog->cleanTable();
        $this->stagingLog->cleanTable();
    }

    #[DbIsolation(false)]
    #[AppIsolation(true)]
    #[Config('catalog/price/scope', 1)]
    #[Config('lowest_price_logger/general/async_logging_enabled', 1)]
    #[DataFixture(\Magento\Catalog\Test\Fixture\Product::class, ['price' => 10], 'product')]
    public function testAsyncModeQueuesObservedPricesToStagingOnProductPageView()
    {
        $this->getCurrentDateFake->setValue('2024-01-01');
        $product = DataFixtureStorageManager::getStorage()->get('product');

        $this->dispatch('catalog/product/view/id/' . $product->getId());

        $stagingRows = $this->stagingLog->getBatch(100);
        $this->assertNotEmpty($stagingRows);
        $this->assertEmpty($this->priceHistoryLog->getPriceHistory([$product->getId()]));

        $productIds = array_unique(array_column($stagingRows, 'product_id'));
        $this->assertCount(1, $productIds);
        $this->assertEquals($product->getId(), $productIds[0]);

        $prices = array_column($stagingRows, 'price');
        $this->assertContains('10.000000', $prices);

        foreach (array_column($stagingRows, 'was_autogenerated_by_cron') as $flag) {
            $this->assertEquals(0, $flag);
        }
    }

    #[DbIsolation(false)]
    #[AppIsolation(true)]
    #[Config('catalog/price/scope', 1)]
    #[Config('lowest_price_logger/general/async_logging_enabled', 1)]
    #[DataFixture(\Magento\Catalog\Test\Fixture\Product::class, ['price' => 10], 'product')]
    public function testFullAsyncFlowMovesObservedPricesToLog()
    {
        $this->getCurrentDateFake->setValue('2024-01-01');
        $product = DataFixtureStorageManager::getStorage()->get('product');

        $this->dispatch('catalog/product/view/id/' . $product->getId());
        $this->transferStagedPricesToLog->execute();

        $this->assertEmpty($this->stagingLog->getBatch(100));

        $priceHistory = $this->priceHistoryLog->getPriceHistory([$product->getId()], 1, 0);
        $this->assertNotEmpty($priceHistory);
        $this->assertEquals(10, $priceHistory[0]['price']);
        $this->assertEquals('2024-01-01', $priceHistory[0]['log_date']);
        $this->assertEquals(0, $priceHistory[0]['was_autogenerated_by_cron']);
    }

    #[DbIsolation(false)]
    #[AppIsolation(true)]
    #[Config('catalog/price/scope', 1)]
    #[Config('lowest_price_logger/general/async_logging_enabled', 1)]
    #[DataFixture(\Magento\Catalog\Test\Fixture\Product::class, ['price' => 10], 'product')]
    public function testSecondDispatchWithSamePriceDoesNotDuplicateInLog()
    {
        $this->getCurrentDateFake->setValue('2024-01-01');
        $product = DataFixtureStorageManager::getStorage()->get('product');

        $this->dispatch('catalog/product/view/id/' . $product->getId());
        $this->transferStagedPricesToLog->execute();

        $this->dispatch('catalog/product/view/id/' . $product->getId());
        $this->transferStagedPricesToLog->execute();

        $priceHistory = $this->priceHistoryLog->getPriceHistory([$product->getId()], 1, 0);
        $this->assertCount(1, $priceHistory);
        $this->assertEquals(10, $priceHistory[0]['price']);
    }

    public function tearDown(): void
    {
        $this->priceHistoryLog->cleanTable();
        $this->stagingLog->cleanTable();
    }
}