<?php

namespace MageSuite\LowestPriceLogger\Test\Integration;

class LogLowestPriceTest extends \PHPUnit\Framework\TestCase
{
    protected ?\MageSuite\LowestPriceLogger\Model\GenerateLowestPriceForAllProducts $generateLowestPriceForAllProducts;
    protected ?\Magento\Framework\App\ObjectManager $objectManager;
    protected ?\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog $priceHistoryLog;
    protected ?\Magento\Catalog\Api\ProductRepositoryInterface $productRepository;
    protected ?GetCurrentDateFake $getCurrentDateFake;
    protected ?\Magento\Store\Model\WebsiteFactory $websiteFactory;

    public function setUp(): void
    {
        $this->objectManager = \Magento\TestFramework\ObjectManager::getInstance();
        $this->getCurrentDateFake = new GetCurrentDateFake();

        $this->generateLowestPriceForAllProducts = $this->objectManager->create(
            \MageSuite\LowestPriceLogger\Model\GenerateLowestPriceForAllProducts::class,
            ['getCurrentDate' => $this->getCurrentDateFake]
        );

        $this->priceHistoryLog = $this->objectManager->get(\MageSuite\LowestPriceLogger\Model\ResourceModel\PriceHistoryLog::class);
        $this->productRepository = $this->objectManager->get(\Magento\Catalog\Api\ProductRepositoryInterface::class);
        $this->websiteFactory = $this->objectManager->create(\Magento\Store\Model\WebsiteFactory::class);
    }

    /**
     * Batch size is set to 1 to ensure pagination of products works correctly
     * @magentoAdminConfigFixture lowest_price_logger/processing/batch_size 1
     * @magentoDbIsolation disabled
     * @magentoAppIsolation enabled
     * @magentoConfigFixture default/catalog/price/scope 1
     * @magentoDataFixture MageSuite_LowestPriceLogger::Test/Integration/_files/product.php
     */
    public function testItLogsPricesFromDifferentWebsites()
    {
        $this->getCurrentDateFake->setValue('2022-08-02');

        $this->generateLowestPriceForAllProducts->execute();

        $product = $this->productRepository->get('simple');

        $defaultWebsitePriceHistory = $this->priceHistoryLog->getPriceHistory([$product->getId()], $this->getDefaultWebsiteId(), 0);

        $this->assertEquals(10, $defaultWebsitePriceHistory[0]['price']);
        $this->assertEquals(1, $defaultWebsitePriceHistory[0]['was_autogenerated_by_cron']);

        $secondWebsitePriceHistory = $this->priceHistoryLog->getPriceHistory([$product->getId()], $this->getSecondWebsiteId(), 0);

        $this->assertEquals(8, $secondWebsitePriceHistory[0]['price']);
        $this->assertEquals(5.99, $secondWebsitePriceHistory[1]['price']);

        $secondProduct = $this->productRepository->get('simple_second');
        $secondProductPriceHistory = $this->priceHistoryLog->getPriceHistory([$secondProduct->getId()], $this->getDefaultWebsiteId());

        $this->assertEquals(12, $secondProductPriceHistory[0]['price']);
    }

    /**
     * @magentoDbIsolation disabled
     * @magentoAppIsolation enabled
     * @magentoConfigFixture default/catalog/price/scope 1
     * @magentoDataFixture MageSuite_LowestPriceLogger::Test/Integration/_files/product.php
     */
    public function testItOnlyLogsChangesBetweenDays()
    {
        $this->getCurrentDateFake->setValue('2022-08-02');
        $this->generateLowestPriceForAllProducts->execute();

        $product = $this->productRepository->get('simple', true, 1, true);
        $product->setPrice(9.00);
        $this->productRepository->save($product);

        $this->getCurrentDateFake->setValue('2022-08-03');
        $this->generateLowestPriceForAllProducts->execute();

        $priceHistory = $this->priceHistoryLog->getPriceHistory([$product->getId()], $this->getDefaultWebsiteId(), 0);

        $this->assertEquals(10, $priceHistory[0]['price']);
        $this->assertEquals('2022-08-02', $priceHistory[0]['log_date']);
        $this->assertEquals(9, $priceHistory[1]['price']);
        $this->assertEquals('2022-08-03', $priceHistory[1]['log_date']);

        $priceHistory = $this->priceHistoryLog->getPriceHistory([$product->getId()], $this->getSecondWebsiteId(), 0);

        $this->assertCount(2, $priceHistory);
        $this->assertEquals('2022-08-02', $priceHistory[0]['log_date']);
        $this->assertEquals('2022-08-02', $priceHistory[1]['log_date']);
    }

    /**
     * @magentoDbIsolation disabled
     * @magentoAppIsolation enabled
     * @magentoConfigFixture default/catalog/price/scope 1
     * @magentoDataFixture MageSuite_LowestPriceLogger::Test/Integration/_files/product_with_tier_price.php
     */
    public function testItLogsTierPrice()
    {
        $this->getCurrentDateFake->setValue('2022-08-02');
        $this->generateLowestPriceForAllProducts->execute();

        $product = $this->productRepository->get('simple', true, 1, true);

        $priceHistory = $this->priceHistoryLog->getPriceHistory([$product->getId()], $this->getDefaultWebsiteId(), 1);

        $this->assertEquals(10, $priceHistory[0]['price']);
        $this->assertEquals('2022-08-02', $priceHistory[0]['log_date']);
        $this->assertEquals(4.99, $priceHistory[1]['price']);
        $this->assertEquals('2022-08-02', $priceHistory[1]['log_date']);
    }

    /**
     * @magentoDbIsolation disabled
     * @magentoAppIsolation enabled
     * @magentoConfigFixture default/catalog/price/scope 1
     * @magentoDataFixture MageSuite_LowestPriceLogger::Test/Integration/_files/product_with_catalog_rule.php
     */
    public function testItLogsCatalogRulePrice()
    {
        $this->getCurrentDateFake->setValue('2022-08-02');
        $this->generateLowestPriceForAllProducts->execute();

        $product = $this->productRepository->get('simple', true, 1, true);

        $priceHistory = $this->priceHistoryLog->getPriceHistory([$product->getId()], $this->getDefaultWebsiteId(), 0);

        $this->assertEquals(10, $priceHistory[0]['price']);
        $this->assertEquals('2022-08-02', $priceHistory[0]['log_date']);
        $this->assertEquals(8.50, $priceHistory[1]['price']);
        $this->assertEquals('2022-08-02', $priceHistory[1]['log_date']);
    }

    public function tearDown(): void
    {
        $this->priceHistoryLog->cleanTable();
    }

    public function getDefaultWebsiteId()
    {
        $website = $this->websiteFactory->create();
        $website->load('base', 'code');
        return $website->getId();
    }

    public function getSecondWebsiteId()
    {
        $website = $this->websiteFactory->create();
        $website->load('test', 'code');
        return $website->getId();
    }
}
